config/routes.rb
Rails.application.routes.draw do
  resources :channels

  resources :people

  resources :addresses

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :user
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)
    @channel.user = current_user

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :provider, :client_id, :client_secret, :last_login_at, :user_id)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for @channel, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :provider, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :provider, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :client_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :client_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :client_secret, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :client_secret, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_login_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :last_login_at, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  channels_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/channels/edit.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Channel %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/index.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => Channel %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:client_id) %></th>
      <th><%= model_class.human_attribute_name(:client_secret) %></th>
      <th><%= model_class.human_attribute_name(:last_login_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.id %></td>
        <td><%= channel.name %></td>
        <td><%= channel.provider %></td>
        <td><%= channel.client_id %></td>
        <td><%= channel.client_secret %></td>
        <td><%= channel.last_login_at %></td>
        <td><%=l channel.created_at, format: :long %></td>
        <td>
          <%= link_to channel_path(channel), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to channel_path(channel), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_channel_path,
            :class => 'btn btn-primary' %>

app/views/channels/new.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Channel %></h1>
</div>
<%= render :partial => 'form' %>

app/views/channels/show.html.erb
<%- model_class = Channel -%>
<div class="page-header">
  <h1><%=t '.title', :default => Channel %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @channel.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:provider) %></dt>
      <dd><pre class="prettyprint"><%= @channel.provider %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_id) %></dt>
      <dd><pre class="prettyprint"><%= @channel.client_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:client_secret) %></dt>
      <dd><pre class="prettyprint"><%= @channel.client_secret %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_login_at) %></dt>
      <dd><pre class="prettyprint"><%= @channel.last_login_at %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              channels_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_channel_path(@channel), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              channel_path(@channel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>